[package]
authors       = ["강동윤 <kdy1997.dev@gmail.com>"]
description   = "ES2021 compatibility transforms"
documentation = "https://rustdoc.swc.rs/swc_ecma_compat_es2021/"
edition       = "2021"
include       = ["Cargo.toml", "src/**/*.rs"]
license       = "Apache-2.0"
name          = "swc_ecma_compat_es2021"
repository    = "https://github.com/swc-project/swc.git"
version       = "5.0.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = { workspace = true }

swc_atoms                = { version = "2.0.0", path = "../swc_atoms" }
swc_common               = { version = "4.0.0", path = "../swc_common" }
swc_ecma_ast             = { version = "4.0.1", path = "../swc_ecma_ast" }
swc_ecma_transforms_base = { version = "5.0.1", path = "../swc_ecma_transforms_base" }
swc_ecma_utils           = { version = "5.0.0", path = "../swc_ecma_utils" }
swc_ecma_visit           = { version = "4.0.0", path = "../swc_ecma_visit" }
swc_trace_macro          = { version = "2.0.0", path = "../swc_trace_macro" }
