[package]
authors       = ["강동윤 <kdy1997.dev@gmail.com>"]
description   = "Port of stylis"
documentation = "https://rustdoc.swc.rs/swc_css_compat/"
edition       = "2021"
include       = ["Cargo.toml", "src/**/*.rs", "src/**/*.json", "data/**/*.json"]
license       = "Apache-2.0"
name          = "swc_css_compat"
repository    = "https://github.com/swc-project/swc.git"
version       = "4.0.0"

[lib]
bench = false

[dependencies]
bitflags   = { workspace = true }
once_cell  = { workspace = true }
serde      = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

swc_atoms     = { version = "2.0.0", path = "../swc_atoms" }
swc_common    = { version = "4.0.0", path = "../swc_common" }
swc_css_ast   = { version = "4.0.1", path = "../swc_css_ast" }
swc_css_utils = { version = "4.0.0", path = "../swc_css_utils/" }
swc_css_visit = { version = "4.0.0", path = "../swc_css_visit" }

[dev-dependencies]
swc_css_codegen = { version = "4.0.0", path = "../swc_css_codegen" }
swc_css_parser  = { version = "4.0.0", path = "../swc_css_parser" }
testing         = { version = "4.0.0", path = "../testing" }
