[package]
authors       = ["강동윤 <kdy1997.dev@gmail.com>"]
description   = "Macros to prevent mistakes"
documentation = "https://rustdoc.swc.rs/swc_config_macro/"
edition       = "2021"
license       = "Apache-2.0"
name          = "swc_config_macro"
repository    = "https://github.com/swc-project/swc.git"
version       = "1.0.0"

[lib]
bench      = false
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote       = { workspace = true }
syn         = { workspace = true }

swc_macros_common = { version = "1.0.0", path = "../swc_macros_common" }
