[package]
authors       = ["강동윤 <kdy1997.dev@gmail.com>"]
description   = "Helper for transforms for the swc project"
documentation = "https://rustdoc.swc.rs/swc_ecma_transforms_classes/"
edition       = "2021"
license       = "Apache-2.0"
name          = "swc_ecma_transforms_classes"
repository    = "https://github.com/swc-project/swc.git"
version       = "5.0.0"

[lib]
bench = false

[dependencies]
swc_atoms                = { version = "2.0.0", path = "../swc_atoms" }
swc_common               = { version = "4.0.0", path = "../swc_common" }
swc_ecma_ast             = { version = "4.0.1", path = "../swc_ecma_ast" }
swc_ecma_transforms_base = { version = "5.0.1", path = "../swc_ecma_transforms_base" }
swc_ecma_utils           = { version = "5.0.0", path = "../swc_ecma_utils" }
swc_ecma_visit           = { version = "4.0.0", path = "../swc_ecma_visit" }
